# Process Wrangling

## Import Library

In [1]:
# !pip install deep_translator

In [2]:
import pandas as pd
from deep_translator import GoogleTranslator
import time
pd.options.display.max_colwidth = None

In [3]:
df = pd.read_csv('Data-Done/undersampled_dataset.csv')
df

,Tweet,Label
0,<user> <user> yes but boring af 😭,0
1,sweet dreams 😘 <hashtag> girlsgeneration <url>,0
2,<user> all that 🍑 in them dress pants 😱 <url>,0
3,"<user> <user> mbn , i hate being single 😿",0
4,"<user> only a pleasure, carolyn 😊",0
...,...,...
18573,what is color is that ghetto fly super friend slang👩🏾‍🤝‍🧑🏼,1
18574,i am a brand new member from the south jersey area with a nigger at my house👅,1
18575,you could try looking at the national socialist and fascist resource center at hyper text transfer protocol www ufc co uk they cover a whole range of educational material🤮🤢🤢,1
18576,i what a slut wondering the same thing when i first saw that this section what a slut added🤤,1
18577,although i am not an old fart i am in ur moms pussy💩💩💩💩,1

In [4]:
# Check Missing and Duplicated Values
print("Missing Values:")
print(df.isnull().sum())
print("\nDuplicated Values:")
print(df.duplicated().sum())

Missing Values:
Tweet    0
Label    0
dtype: int64

Duplicated Values:
1289

In [5]:
# Drop Duplicates
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [6]:
# Check Missing and Duplicated Values
print("Missing Values:")
print(df.isnull().sum())
print("\nDuplicated Values:")
print(df.duplicated().sum())

Missing Values:
Tweet    0
Label    0
dtype: int64

Duplicated Values:
0

In [7]:
# Translate Column Tweet
def translate_text(text, source='en', target='id', retries=3):
    """
    Fungsi untuk menerjemahkan teks dengan mekanisme retry jika terjadi error.
    """
    for attempt in range(retries):
        try:
            translated_text = GoogleTranslator(source=source, target=target).translate(text)
            return translated_text
        except Exception as e:
            print(f"Error occurred: {e} - Retrying ({attempt+1}/{retries})")
            time.sleep(5)  # Tunggu sebelum mencoba lagi
    return None  # Jika gagal setelah semua percobaan, kembalikan None

In [8]:
# Start TIMER 
start_time = time.time()

# Translating 'Tweet'
df['Tweet_Translated'] = df['Tweet'].apply(lambda x: translate_text(x, source='en', target='id'))

# Stop TIMER 
end_time = time.time()
elapsed_time = end_time - start_time

# Print execution time
print(f"\n✅ Translation completed in {elapsed_time:.2f} seconds ⏳")

Error occurred: @JfaithGates she said she got FUCKING BLOOD ON HER HAND 😭😭😭😭😭😭 I SAID NOOO --> No translation was found using the current translator. Try another translator? - Retrying (1/3)
Error occurred: i always feel so nasty after eating ice cream 😹 like damn you indulgent btch. --> No translation was found using the current translator. Try another translator? - Retrying (1/3)
Error occurred: RT @Laryonce_: If I say I got you I got you nobody can make me stop fucking with you but you. 🤞🏽 --> No translation was found using the current translator. Try another translator? - Retrying (1/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=%3Cuser%3E+hey+there+sexy%21++%F0%9F%98%98+come+sit+on+my+dick+and+dance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DAD9BD3C50>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine')) - Retrying (1/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=%3Cuser%3E+hey+there+sexy%21++%F0%9F%98%98+come+sit+on+my+dick+and+dance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DADA0C93A0>: Failed to resolve 'translate.google.com' ([Errno 11001] getaddrinfo failed)")) - Retrying (2/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=%3Cuser%3E+hey+there+sexy%21++%F0%9F%98%98+come+sit+on+my+dick+and+dance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DAD9BA8FE0>: Failed to resolve 'translate.google.com' ([Errno 11001] getaddrinfo failed)")) - Retrying (3/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=%3Cuser%3E+you+look+better+on+your+knees%2C+licking+my+cock+%F0%9F%91%91+%0D%0A%0D%0A%3Curl%3E (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DADA0055B0>: Failed to resolve 'translate.google.com' ([Errno 11001] getaddrinfo failed)")) - Retrying (1/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=billy+bitter+certainly+what+a+slut+a+daredevil+cameraman%F0%9F%91%84 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001DADA0C8EC0>, 'Connection to translate.google.com timed out. (connect timeout=None)')) - Retrying (1/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=billy+bitter+certainly+what+a+slut+a+daredevil+cameraman%F0%9F%91%84 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DAD9D89C70>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine')) - Retrying (2/3)
Error occurred: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=id&sl=en&q=my+skin+color+well+its+white+and+i+hate+niggerrrrssss%F0%9F%A4%A2%F0%9F%A4%AE (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001DADA0C9220>, 'Connection to translate.google.com timed out. (connect timeout=None)')) - Retrying (1/3)
Error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) - Retrying (2/3)

✅ Translation completed in 14140.22 seconds ⏳

In [9]:
df

,Tweet,Label,Tweet_Translated
0,<user> <user> yes but boring af 😭,0,<user> <user> ya tapi boring af 😭
1,sweet dreams 😘 <hashtag> girlsgeneration <url>,0,Mimpi indah 😘 <hashtag> GirlsGeneration <RURL>
2,<user> all that 🍑 in them dress pants 😱 <url>,0,<user> Semua itu 🍑 di dalamnya celana berpakaian 😱 <url>
3,"<user> <user> mbn , i hate being single 😿",0,"<user> <user> mbn, saya benci menjadi lajang 😿"
4,"<user> only a pleasure, carolyn 😊",0,"<user> Hanya menyenangkan, Carolyn 😊"
...,...,...,...
17284,what is color is that ghetto fly super friend slang👩🏾‍🤝‍🧑🏼,1,Apa warnanya adalah ghetto fly super friend slang👩🏾‍🤝‍🧑🏼
17285,i am a brand new member from the south jersey area with a nigger at my house👅,1,Saya anggota baru dari daerah Jersey Selatan dengan negro di rumah saya👅
17286,you could try looking at the national socialist and fascist resource center at hyper text transfer protocol www ufc co uk they cover a whole range of educational material🤮🤢🤢,1,Anda dapat mencoba melihat Pusat Sumber Daya Sosialis dan Fasis Nasional di Hyper Text Transfer Protocol www ufc co uk mereka mencakup berbagai macam materi pendidikan🤮🤢🤢
17287,i what a slut wondering the same thing when i first saw that this section what a slut added🤤,1,I Sungguh pelacur yang bertanya -tanya hal yang sama ketika saya pertama kali melihat bagian ini yang ditambahkan pelacur🤤
17288,although i am not an old fart i am in ur moms pussy💩💩💩💩,1,"Meskipun saya bukan kentut tua, saya di vagina ibu Anda💩💩💩💩"

In [10]:
df_translated = df[['Tweet_Translated', 'Label']]
df_translated.to_csv('Data-Done/translated_dataset.csv', index=False)